#+title: Seshat Global History Databank Text Dataset and Benchmark of Large Language Models' History Knowledge
#+OPTIONS: author:nil date:nil

* Dataset links
[[https://github.com/seshat-db/NeurIPS_2024_Seshat_Benchmark][Dataset Repository (Github)]] 
[[https://github.com/seshat-db/NeurIPS_2024_Seshat_Benchmark/blob/main/croissant.json][Croissant Metadata (Github)]]
* Usage
This dataset can be used to benchmark LLMs on their expert level history knowledge.
* License/Responsiblity
This dataset is licensed under [[https://creativecommons.org/licenses/by/4.0/][CC by 4.0]].
The authors bear all responsibility in case this dataset contains violations of rights.
* Dataset preservation/DOI
Upon acceptance we will publish the dataset on [[https://zenodo.org/][Zenodo]] with a respective DOI, as to ensure long term preservation of the dataset.
* Loading the dataset
#+begin_src python :results output
import pandas as pd
df = pd.read_parquet("dataset.parquet")
#+end_src

* Dataset Metadata
Dataset metadata documented in the =croissant.json= file.


* Model Fingerprints
When model fingerprint are available we created extra columns for each model fingerprint. These columns are named via the following pattern =<model-name>_<model-fingerprint>=.

* Column Descriptions
** Q
  The multiple choice question.
** A
  The expected completion of the prompt.
** polity old id
  ID for polity according to Seshat ids.
** start year str
  String for when polity started existing (in BCE/CE format).
** end year str
  String for when polity stopped existing (in BCE/CE format).
** start year int
  Int for when polity started existing (in BCE/CE format).
** end year int
  Int for when polity stopped existing (in BCE/CE format).
** name
  Polity name.
** nga
  Natural Geographic Area for Polity.
** category
  Immediate parent category of fact from Seshat codebook.
** root cat
  Root category of fact from Seshat codebook.
** seshat value
  Value of fact in Seshat.
** request id
  Request id for openai batch requests.
** n shot examples
  4-shot examples as json string.
** openai message
  Full query including system messages as json string.
** gpt4-o
  Responses for gpt4-o model.
** meta-llama/Llama-3-70b-chat-hf
  Responses for meta-llama/Llama-3-70b-chat-hf model.
** gpt-4-turbo-2024-04-09
  Responses for gpt-4-turbo-2024-04-09 model.
** region
  World region for fact.
** description
  Description provided by RAs for fact.
** raw reference text
  Raw reference text for fact source material.
** bibtex json
  Bibtex json string for fact source material.
** zotero id
  Zotero ID for Seshat internal reference.
